-- MySQL Script generated by MySQL Workbench
-- Mon Jun 26 14:42:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_db` DEFAULT CHARACTER SET utf8 ;
USE `app_db` ;

-- -----------------------------------------------------
-- Table `app_db`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`students` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NULL,
  `surname` VARCHAR(16) NULL,
  `group_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `group_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_students_groups1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `app_db`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`teachers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NULL,
  `surname` VARCHAR(16) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`subjects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(45) NULL,
  `teachers_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `teachers_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_subjects_teachers1_idx` (`teachers_id` ASC) VISIBLE,
  CONSTRAINT `fk_subjects_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `app_db`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`grades` (
  `grade` INT NOT NULL,
  `subjects_id` INT UNSIGNED NOT NULL,
  `students_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`grade`, `subjects_id`, `students_id`),
  INDEX `fk_grades_subjects1_idx` (`subjects_id` ASC) VISIBLE,
  INDEX `fk_grades_students1_idx` (`students_id` ASC) VISIBLE,
  CONSTRAINT `fk_grades_subjects1`
    FOREIGN KEY (`subjects_id`)
    REFERENCES `app_db`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `app_db`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_db`.`groupSubjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_db`.`groupSubjects` (
  `groups_id` INT UNSIGNED NOT NULL,
  `subjects_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`groups_id`, `subjects_id`),
  INDEX `fk_groupSubjects_subjects1_idx` (`subjects_id` ASC) VISIBLE,
  CONSTRAINT `fk_groupSubjects_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `app_db`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupSubjects_subjects1`
    FOREIGN KEY (`subjects_id`)
    REFERENCES `app_db`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
